/**
 * Kanji data banks for JLPTQuizPage
 * Separated for maintainability — imported by JLPTQuizPage.jsx
 */

export const kanjiByLevel = {
    N5: [
        { kanji: '食べる', correctReading: 'たべる', meaning: 'To eat', wrongReadings: ['しょくべる', 'くべる', 'たぶる'] },
        { kanji: '飲む', correctReading: 'のむ', meaning: 'To drink', wrongReadings: ['いんむ', 'のめ', 'のぶ'] },
        { kanji: '見る', correctReading: 'みる', meaning: 'To see', wrongReadings: ['けんる', 'みえる', 'にる'] },
        { kanji: '聞く', correctReading: 'きく', meaning: 'To listen', wrongReadings: ['ぶんく', 'もんく', 'きこ'] },
        { kanji: '読む', correctReading: 'よむ', meaning: 'To read', wrongReadings: ['どくむ', 'よぶ', 'とむ'] },
        { kanji: '書く', correctReading: 'かく', meaning: 'To write', wrongReadings: ['しょく', 'がく', 'かき'] },
        { kanji: '話す', correctReading: 'はなす', meaning: 'To speak', wrongReadings: ['わす', 'かたす', 'はなし'] },
        { kanji: '買う', correctReading: 'かう', meaning: 'To buy', wrongReadings: ['ばいう', 'かい', 'まう'] },
        { kanji: '入る', correctReading: 'はいる', meaning: 'To enter', wrongReadings: ['いる', 'にゅうる', 'いれる'] },
        { kanji: '出る', correctReading: 'でる', meaning: 'To exit', wrongReadings: ['しゅつる', 'だる', 'だす'] },
        { kanji: '学校', correctReading: 'がっこう', meaning: 'School', wrongReadings: ['がくこう', 'がっきょう', 'まなこう'] },
        { kanji: '先生', correctReading: 'せんせい', meaning: 'Teacher', wrongReadings: ['さきせい', 'せんしょう', 'せいせん'] },
        { kanji: '大学', correctReading: 'だいがく', meaning: 'University', wrongReadings: ['おおがく', 'たいがく', 'だいまな'] },
        { kanji: '電話', correctReading: 'でんわ', meaning: 'Telephone', wrongReadings: ['でんは', 'てんわ', 'かみなりわ'] },
        { kanji: '時間', correctReading: 'じかん', meaning: 'Time', wrongReadings: ['ときま', 'しかん', 'じけん'] },
        { kanji: '友達', correctReading: 'ともだち', meaning: 'Friend', wrongReadings: ['ゆうだち', 'ゆうたつ', 'ともたち'] },
        { kanji: '天気', correctReading: 'てんき', meaning: 'Weather', wrongReadings: ['あまき', 'てんけ', 'てんぎ'] },
        { kanji: '毎日', correctReading: 'まいにち', meaning: 'Every day', wrongReadings: ['まいび', 'まいひ', 'まいじつ'] },
        { kanji: '今日', correctReading: 'きょう', meaning: 'Today', wrongReadings: ['こんにち', 'いまにち', 'こんじつ'] },
        { kanji: '来年', correctReading: 'らいねん', meaning: 'Next year', wrongReadings: ['きねん', 'くねん', 'らいとし'] },
    ],
    N4: [
        { kanji: '開ける', correctReading: 'あける', meaning: 'To open', wrongReadings: ['かいける', 'ひらける', 'あく'] },
        { kanji: '届ける', correctReading: 'とどける', meaning: 'To deliver', wrongReadings: ['かいける', 'つける', 'わたける'] },
        { kanji: '届く', correctReading: 'とどく', meaning: 'To arrive/reach', wrongReadings: ['かいく', 'つく', 'わたく'] },
        { kanji: '引っ越す', correctReading: 'ひっこす', meaning: 'To move (house)', wrongReadings: ['いんこす', 'ひきこす', 'ひこす'] },
        { kanji: '建てる', correctReading: 'たてる', meaning: 'To build', wrongReadings: ['けんてる', 'じてる', 'かてる'] },
        { kanji: '受ける', correctReading: 'うける', meaning: 'To receive', wrongReadings: ['じゅける', 'おける', 'つける'] },
        { kanji: '運転', correctReading: 'うんてん', meaning: 'Driving', wrongReadings: ['うんでん', 'うてん', 'えんてん'] },
        { kanji: '特別', correctReading: 'とくべつ', meaning: 'Special', wrongReadings: ['とっべつ', 'どくべつ', 'とくわけ'] },
        { kanji: '季節', correctReading: 'きせつ', meaning: 'Season', wrongReadings: ['きぶし', 'きせち', 'しせつ'] },
        { kanji: '文化', correctReading: 'ぶんか', meaning: 'Culture', wrongReadings: ['もんか', 'ぶんけ', 'もじか'] },
        { kanji: '番組', correctReading: 'ばんぐみ', meaning: 'TV program', wrongReadings: ['ばんくみ', 'ばんそ', 'はんくみ'] },
        { kanji: '国際', correctReading: 'こくさい', meaning: 'International', wrongReadings: ['くにさい', 'こくざい', 'こくせい'] },
        { kanji: '生活', correctReading: 'せいかつ', meaning: 'Life/Living', wrongReadings: ['しょうかつ', 'なまかつ', 'せいこう'] },
        { kanji: '理由', correctReading: 'りゆう', meaning: 'Reason', wrongReadings: ['りゅう', 'りゆ', 'わけゆう'] },
        { kanji: '世界', correctReading: 'せかい', meaning: 'World', wrongReadings: ['よかい', 'せいかい', 'しかい'] },
        { kanji: '台風', correctReading: 'たいふう', meaning: 'Typhoon', wrongReadings: ['だいかぜ', 'たいかぜ', 'だいふう'] },
        { kanji: '地震', correctReading: 'じしん', meaning: 'Earthquake', wrongReadings: ['ちしん', 'じふるえ', 'ちふるえ'] },
        { kanji: '経験', correctReading: 'けいけん', meaning: 'Experience', wrongReadings: ['きょうけん', 'けいげん', 'きけん'] },
        { kanji: '安全', correctReading: 'あんぜん', meaning: 'Safety', wrongReadings: ['やすぜん', 'あんせん', 'あんまん'] },
        { kanji: '無理', correctReading: 'むり', meaning: 'Impossible', wrongReadings: ['ぶり', 'なしり', 'むわり'] },
    ],
    N3: [
        { kanji: '会議', correctReading: 'かいぎ', meaning: 'Meeting', wrongReadings: ['かいき', 'かぎ', 'あいぎ'] },
        { kanji: '研究', correctReading: 'けんきゅう', meaning: 'Research', wrongReadings: ['けんく', 'げんきゅう', 'けんぐう'] },
        { kanji: '政治', correctReading: 'せいじ', meaning: 'Politics', wrongReadings: ['しょうじ', 'せいち', 'まさじ'] },
        { kanji: '産業', correctReading: 'さんぎょう', meaning: 'Industry', wrongReadings: ['さんごう', 'せんぎょう', 'さんきょう'] },
        { kanji: '自然', correctReading: 'しぜん', meaning: 'Nature', wrongReadings: ['じねん', 'しせん', 'じぜん'] },
        { kanji: '交通', correctReading: 'こうつう', meaning: 'Traffic', wrongReadings: ['こうとう', 'きょうつう', 'こうずう'] },
        { kanji: '制度', correctReading: 'せいど', meaning: 'System', wrongReadings: ['しど', 'せいと', 'さいど'] },
        { kanji: '技術', correctReading: 'ぎじゅつ', meaning: 'Technology', wrongReadings: ['きじゅつ', 'ぎじつ', 'きしゅつ'] },
        { kanji: '教育', correctReading: 'きょういく', meaning: 'Education', wrongReadings: ['きゅういく', 'きょうく', 'こういく'] },
        { kanji: '関係', correctReading: 'かんけい', meaning: 'Relationship', wrongReadings: ['かんかい', 'かんけ', 'がんけい'] },
        { kanji: '反対', correctReading: 'はんたい', meaning: 'Opposite', wrongReadings: ['はんだい', 'ほんたい', 'ばんたい'] },
        { kanji: '問題', correctReading: 'もんだい', meaning: 'Problem', wrongReadings: ['もだい', 'もんてい', 'とだい'] },
        { kanji: '決定', correctReading: 'けってい', meaning: 'Decision', wrongReadings: ['けつてい', 'けつじょう', 'きめてい'] },
        { kanji: '規則', correctReading: 'きそく', meaning: 'Rule', wrongReadings: ['きぞく', 'きのり', 'ぐそく'] },
        { kanji: '記念', correctReading: 'きねん', meaning: 'Memorial', wrongReadings: ['きめん', 'きなん', 'きえん'] },
        { kanji: '相談', correctReading: 'そうだん', meaning: 'Consultation', wrongReadings: ['あいだん', 'そうたん', 'しょうだん'] },
        { kanji: '設計', correctReading: 'せっけい', meaning: 'Design/Plan', wrongReadings: ['せつけい', 'もうけい', 'せきけい'] },
        { kanji: '調査', correctReading: 'ちょうさ', meaning: 'Investigation', wrongReadings: ['しらべさ', 'ちょうし', 'きょうさ'] },
        { kanji: '成功', correctReading: 'せいこう', meaning: 'Success', wrongReadings: ['なりこう', 'じょうこう', 'せいく'] },
        { kanji: '失敗', correctReading: 'しっぱい', meaning: 'Failure', wrongReadings: ['しつはい', 'しっぱ', 'しばい'] },
        { kanji: '練習', correctReading: 'れんしゅう', meaning: 'Practice', wrongReadings: ['ねりしゅう', 'れんしう', 'ねんしゅう'] },
        { kanji: '準備', correctReading: 'じゅんび', meaning: 'Preparation', wrongReadings: ['しゅんび', 'じゅんぴ', 'じゅんべ'] },
        { kanji: '説明', correctReading: 'せつめい', meaning: 'Explanation', wrongReadings: ['しょうめい', 'せつめ', 'せいめい'] },
        { kanji: '約束', correctReading: 'やくそく', meaning: 'Promise', wrongReadings: ['やくしょく', 'やくたば', 'わくそく'] },
        { kanji: '注意', correctReading: 'ちゅうい', meaning: 'Caution', wrongReadings: ['ちゅうぎ', 'そそい', 'じゅうい'] },
        { kanji: '想像', correctReading: 'そうぞう', meaning: 'Imagination', wrongReadings: ['しょうぞう', 'そうじょう', 'おもぞう'] },
        { kanji: '表現', correctReading: 'ひょうげん', meaning: 'Expression', wrongReadings: ['おもてげん', 'ひょうけん', 'ひょうえん'] },
        { kanji: '連絡', correctReading: 'れんらく', meaning: 'Contact', wrongReadings: ['つらなりらく', 'れんらき', 'ねんらく'] },
        { kanji: '努力', correctReading: 'どりょく', meaning: 'Effort', wrongReadings: ['ぬりょく', 'どりき', 'のりょく'] },
        { kanji: '確認', correctReading: 'かくにん', meaning: 'Confirmation', wrongReadings: ['たしにん', 'きゃくにん', 'かくじん'] },
        { kanji: '影響', correctReading: 'えいきょう', meaning: 'Influence', wrongReadings: ['かげひびき', 'えきょう', 'いんきょう'] },
        { kanji: '経済', correctReading: 'けいざい', meaning: 'Economy', wrongReadings: ['きょうざい', 'けいさい', 'けざい'] },
        { kanji: '選挙', correctReading: 'せんきょ', meaning: 'Election', wrongReadings: ['えらぶきょ', 'せんこ', 'ぜんきょ'] },
        { kanji: '比較', correctReading: 'ひかく', meaning: 'Comparison', wrongReadings: ['くらべかく', 'ひこう', 'ひがく'] },
        { kanji: '退院', correctReading: 'たいいん', meaning: 'Leave hospital', wrongReadings: ['たいえん', 'だいいん', 'しりぞきいん'] },
        { kanji: '貿易', correctReading: 'ぼうえき', meaning: 'Trade', wrongReadings: ['もうえき', 'ぼうやく', 'ぼうき'] },
        { kanji: '講演', correctReading: 'こうえん', meaning: 'Lecture', wrongReadings: ['きょうえん', 'こうべん', 'こえん'] },
        { kanji: '参加', correctReading: 'さんか', meaning: 'Participation', wrongReadings: ['さんが', 'まいか', 'しんか'] },
        { kanji: '複雑', correctReading: 'ふくざつ', meaning: 'Complicated', wrongReadings: ['おくざつ', 'ふくさつ', 'ふくぞう'] },
        { kanji: '環境', correctReading: 'かんきょう', meaning: 'Environment', wrongReadings: ['かんけい', 'わんきょう', 'かんぎょう'] },
        { kanji: '伝統', correctReading: 'でんとう', meaning: 'Tradition', wrongReadings: ['つたとう', 'でんすべ', 'てんとう'] },
        { kanji: '独立', correctReading: 'どくりつ', meaning: 'Independence', wrongReadings: ['ひとりりつ', 'どくり', 'どくだち'] },
        { kanji: '完成', correctReading: 'かんせい', meaning: 'Completion', wrongReadings: ['かんじょう', 'まんせい', 'がんせい'] },
        { kanji: '観光', correctReading: 'かんこう', meaning: 'Sightseeing', wrongReadings: ['みこう', 'かんみつ', 'がんこう'] },
        { kanji: '必要', correctReading: 'ひつよう', meaning: 'Necessary', wrongReadings: ['かなよう', 'ひつやく', 'びつよう'] },
        { kanji: '適当', correctReading: 'てきとう', meaning: 'Suitable', wrongReadings: ['まとあてる', 'てきど', 'できとう'] },
        { kanji: '発展', correctReading: 'はってん', meaning: 'Development', wrongReadings: ['はつてん', 'ほってん', 'はつのべ'] },
        { kanji: '判断', correctReading: 'はんだん', meaning: 'Judgment', wrongReadings: ['ばんだん', 'はんたん', 'はぜん'] },
        { kanji: '禁止', correctReading: 'きんし', meaning: 'Prohibition', wrongReadings: ['きんじ', 'ぎんし', 'こんし'] },
    ],
    N2: [
        { kanji: '維持', correctReading: 'いじ', meaning: 'Maintenance', wrongReadings: ['ゆいじ', 'いち', 'いし'] },
        { kanji: '概念', correctReading: 'がいねん', meaning: 'Concept', wrongReadings: ['がいめん', 'かいねん', 'がいなん'] },
        { kanji: '抽象', correctReading: 'ちゅうしょう', meaning: 'Abstract', wrongReadings: ['ちゅうぞう', 'ちゅうしゃ', 'ちゅうじょう'] },
        { kanji: '脅威', correctReading: 'きょうい', meaning: 'Threat', wrongReadings: ['きょうぎ', 'おどい', 'きょうえ'] },
        { kanji: '偏見', correctReading: 'へんけん', meaning: 'Prejudice', wrongReadings: ['へんみ', 'かたけん', 'へんげん'] },
        { kanji: '矛盾', correctReading: 'むじゅん', meaning: 'Contradiction', wrongReadings: ['ほこたて', 'ぼうじゅん', 'むたて'] },
        { kanji: '曖昧', correctReading: 'あいまい', meaning: 'Ambiguous', wrongReadings: ['あいばい', 'あいみ', 'あいむ'] },
        { kanji: '膨大', correctReading: 'ぼうだい', meaning: 'Enormous', wrongReadings: ['ぼだい', 'ふくだい', 'ほうだい'] },
        { kanji: '甚大', correctReading: 'じんだい', meaning: 'Immense', wrongReadings: ['はなだい', 'しんだい', 'じだい'] },
        { kanji: '慎重', correctReading: 'しんちょう', meaning: 'Cautious', wrongReadings: ['しんじゅう', 'ちんちょう', 'しんおも'] },
        { kanji: '把握', correctReading: 'はあく', meaning: 'Grasp/Understand', wrongReadings: ['ばあく', 'はにぎ', 'はおく'] },
        { kanji: '促進', correctReading: 'そくしん', meaning: 'Promotion', wrongReadings: ['しょくしん', 'そくすすむ', 'ぞくしん'] },
        { kanji: '崩壊', correctReading: 'ほうかい', meaning: 'Collapse', wrongReadings: ['くずかい', 'ほかい', 'ぼうかい'] },
        { kanji: '緊張', correctReading: 'きんちょう', meaning: 'Tension', wrongReadings: ['きんはり', 'ぎんちょう', 'きんちゅう'] },
        { kanji: '拡大', correctReading: 'かくだい', meaning: 'Expansion', wrongReadings: ['ひろだい', 'こうだい', 'がくだい'] },
        { kanji: '削減', correctReading: 'さくげん', meaning: 'Reduction', wrongReadings: ['けずげん', 'しゃくげん', 'さくかん'] },
        { kanji: '妥協', correctReading: 'だきょう', meaning: 'Compromise', wrongReadings: ['たきょう', 'できょう', 'だぎょう'] },
        { kanji: '範囲', correctReading: 'はんい', meaning: 'Scope/Range', wrongReadings: ['はんえ', 'ばんい', 'はんかこ'] },
        { kanji: '傾向', correctReading: 'けいこう', meaning: 'Tendency', wrongReadings: ['かたむこう', 'けいほう', 'けいきょう'] },
        { kanji: '圧倒', correctReading: 'あっとう', meaning: 'Overwhelming', wrongReadings: ['あつとう', 'あっだお', 'あっこう'] },
    ],
    N1: [
        { kanji: '憂鬱', correctReading: 'ゆううつ', meaning: 'Depression/Gloom', wrongReadings: ['うれうつ', 'ゆうつ', 'ゆうう'] },
        { kanji: '齟齬', correctReading: 'そご', meaning: 'Discrepancy', wrongReadings: ['しゃご', 'さご', 'そぐ'] },
        { kanji: '顛末', correctReading: 'てんまつ', meaning: 'Whole story', wrongReadings: ['てんばつ', 'でんまつ', 'てんすえ'] },
        { kanji: '怠惰', correctReading: 'たいだ', meaning: 'Laziness', wrongReadings: ['なまだ', 'たいな', 'おこたり'] },
        { kanji: '忌避', correctReading: 'きひ', meaning: 'Avoidance', wrongReadings: ['いみひ', 'きさけ', 'きび'] },
        { kanji: '恣意', correctReading: 'しい', meaning: 'Arbitrary', wrongReadings: ['じい', 'しぎ', 'しえ'] },
        { kanji: '稀有', correctReading: 'けう', meaning: 'Rare/Unusual', wrongReadings: ['きゆう', 'きう', 'まれゆう'] },
        { kanji: '瞬時', correctReading: 'しゅんじ', meaning: 'Instant', wrongReadings: ['またたきじ', 'しゅんし', 'じゅんじ'] },
        { kanji: '怒濤', correctReading: 'どとう', meaning: 'Surging waves', wrongReadings: ['いかなみ', 'ぬとう', 'どなみ'] },
        { kanji: '搾取', correctReading: 'さくしゅ', meaning: 'Exploitation', wrongReadings: ['しぼしゅ', 'さくとる', 'しゃくしゅ'] },
        { kanji: '疎外', correctReading: 'そがい', meaning: 'Alienation', wrongReadings: ['うとがい', 'そはず', 'そげ'] },
        { kanji: '逸脱', correctReading: 'いつだつ', meaning: 'Deviation', wrongReadings: ['いちだつ', 'いつぬけ', 'いだつ'] },
        { kanji: '薫陶', correctReading: 'くんとう', meaning: 'Mentoring', wrongReadings: ['かおとう', 'くんすえ', 'くんどう'] },
        { kanji: '凡庸', correctReading: 'ぼんよう', meaning: 'Mediocre', wrongReadings: ['はんよう', 'ぼんもち', 'ほんよう'] },
        { kanji: '辛辣', correctReading: 'しんらつ', meaning: 'Harsh/Biting', wrongReadings: ['かららつ', 'しんかつ', 'しんれつ'] },
        { kanji: '杞憂', correctReading: 'きゆう', meaning: 'Needless worry', wrongReadings: ['きうれ', 'きゆ', 'きいう'] },
        { kanji: '躊躇', correctReading: 'ちゅうちょ', meaning: 'Hesitation', wrongReadings: ['しゅうしょ', 'ちゅうしょ', 'ちゅうちゃ'] },
        { kanji: '傲慢', correctReading: 'ごうまん', meaning: 'Arrogance', wrongReadings: ['おごまん', 'こうまん', 'ごまん'] },
        { kanji: '貪欲', correctReading: 'どんよく', meaning: 'Greed', wrongReadings: ['たんよく', 'むさよく', 'とんよく'] },
        { kanji: '恩恵', correctReading: 'おんけい', meaning: 'Grace/Benefit', wrongReadings: ['おんえ', 'おんめぐ', 'いんけい'] },
    ],
}

export const similarKanjiByLevel = {
    N5: [
        { correct: '大', meaning: 'Big', reading: 'おおきい', similars: ['太', '犬', '天'] },
        { correct: '犬', meaning: 'Dog', reading: 'いぬ', similars: ['大', '太', '天'] },
        { correct: '太', meaning: 'Thick/Fat', reading: 'ふとい', similars: ['大', '犬', '天'] },
        { correct: '力', meaning: 'Power', reading: 'ちから', similars: ['刀', '刃', '万'] },
        { correct: '刀', meaning: 'Sword', reading: 'かたな', similars: ['力', '刃', '万'] },
        { correct: '千', meaning: 'Thousand', reading: 'せん', similars: ['干', '于', '午'] },
        { correct: '干', meaning: 'Dry', reading: 'ほす', similars: ['千', '于', '午'] },
        { correct: '午', meaning: 'Noon', reading: 'ご', similars: ['牛', '干', '千'] },
        { correct: '牛', meaning: 'Cow', reading: 'うし', similars: ['午', '半', '年'] },
        { correct: '右', meaning: 'Right', reading: 'みぎ', similars: ['左', '石', '台'] },
        { correct: '左', meaning: 'Left', reading: 'ひだり', similars: ['右', '石', '在'] },
        { correct: '日', meaning: 'Day/Sun', reading: 'ひ', similars: ['目', '白', '田'] },
        { correct: '目', meaning: 'Eye', reading: 'め', similars: ['日', '白', '田'] },
        { correct: '田', meaning: 'Rice field', reading: 'た', similars: ['日', '目', '由'] },
        { correct: '入', meaning: 'Enter', reading: 'はいる', similars: ['人', '八', '込'] },
        { correct: '人', meaning: 'Person', reading: 'ひと', similars: ['入', '八', '大'] },
        { correct: '土', meaning: 'Earth/Soil', reading: 'つち', similars: ['士', '工', '王'] },
        { correct: '士', meaning: 'Samurai', reading: 'し', similars: ['土', '工', '王'] },
        { correct: '水', meaning: 'Water', reading: 'みず', similars: ['氷', '永', '泉'] },
        { correct: '夕', meaning: 'Evening', reading: 'ゆう', similars: ['タ', '久', '多'] },
    ],
    N4: [
        { correct: '待', meaning: 'Wait', reading: 'まつ', similars: ['持', '特', '侍'] },
        { correct: '持', meaning: 'Hold', reading: 'もつ', similars: ['待', '特', '侍'] },
        { correct: '末', meaning: 'End', reading: 'すえ', similars: ['未', '本', '木'] },
        { correct: '未', meaning: 'Not yet', reading: 'み', similars: ['末', '木', '本'] },
        { correct: '方', meaning: 'Direction', reading: 'かた', similars: ['万', '刀', '力'] },
        { correct: '万', meaning: 'Ten thousand', reading: 'まん', similars: ['方', '刀', '力'] },
        { correct: '由', meaning: 'Reason', reading: 'よし', similars: ['田', '甲', '申'] },
        { correct: '申', meaning: 'Say/Monkey', reading: 'もうす', similars: ['由', '甲', '田'] },
        { correct: '氷', meaning: 'Ice', reading: 'こおり', similars: ['水', '永', '泉'] },
        { correct: '忙', meaning: 'Busy', reading: 'いそがしい', similars: ['忘', '忍', '忠'] },
        { correct: '忘', meaning: 'Forget', reading: 'わすれる', similars: ['忙', '忍', '忠'] },
        { correct: '暑', meaning: 'Hot (weather)', reading: 'あつい', similars: ['暮', '者', '署'] },
        { correct: '鳥', meaning: 'Bird', reading: 'とり', similars: ['烏', '島', '鴨'] },
        { correct: '島', meaning: 'Island', reading: 'しま', similars: ['鳥', '烏', '嶋'] },
        { correct: '署', meaning: 'Station/Office', reading: 'しょ', similars: ['暑', '暮', '者'] },
        { correct: '活', meaning: 'Life/Active', reading: 'かつ', similars: ['括', '話', '舌'] },
        { correct: '話', meaning: 'Talk', reading: 'はなし', similars: ['活', '括', '舌'] },
        { correct: '広', meaning: 'Wide', reading: 'ひろい', similars: ['拡', '鉱', '曠'] },
        { correct: '近', meaning: 'Near', reading: 'ちかい', similars: ['斤', '折', '所'] },
        { correct: '週', meaning: 'Week', reading: 'しゅう', similars: ['週', '遇', '道'] },
    ],
    N3: [
        { correct: '減', meaning: 'Decrease', reading: 'へる', similars: ['感', '威', '滅'] },
        { correct: '感', meaning: 'Feel', reading: 'かん', similars: ['減', '威', '滅'] },
        { correct: '議', meaning: 'Discuss', reading: 'ぎ', similars: ['義', '犠', '儀'] },
        { correct: '義', meaning: 'Righteousness', reading: 'ぎ', similars: ['議', '犠', '儀'] },
        { correct: '構', meaning: 'Structure', reading: 'こう', similars: ['講', '溝', '購'] },
        { correct: '講', meaning: 'Lecture', reading: 'こう', similars: ['構', '溝', '購'] },
        { correct: '防', meaning: 'Defend', reading: 'ぼう', similars: ['妨', '坊', '房'] },
        { correct: '妨', meaning: 'Obstruct', reading: 'ぼう', similars: ['防', '坊', '房'] },
        { correct: '複', meaning: 'Duplicate', reading: 'ふく', similars: ['復', '腹', '覆'] },
        { correct: '復', meaning: 'Restore', reading: 'ふく', similars: ['複', '腹', '覆'] },
        { correct: '精', meaning: 'Refined', reading: 'せい', similars: ['清', '晴', '情'] },
        { correct: '清', meaning: 'Clean', reading: 'せい', similars: ['精', '晴', '情'] },
        { correct: '絶', meaning: 'Sever', reading: 'ぜつ', similars: ['説', '脱', '税'] },
        { correct: '説', meaning: 'Theory', reading: 'せつ', similars: ['絶', '脱', '税'] },
        { correct: '状', meaning: 'Condition', reading: 'じょう', similars: ['況', '常', '情'] },
        { correct: '況', meaning: 'Situation', reading: 'きょう', similars: ['状', '常', '情'] },
        { correct: '退', meaning: 'Retreat', reading: 'たい', similars: ['褪', '腿', '追'] },
        { correct: '追', meaning: 'Chase', reading: 'つい', similars: ['退', '褪', '腿'] },
        { correct: '規', meaning: 'Standard', reading: 'き', similars: ['親', '観', '覚'] },
        { correct: '観', meaning: 'Observe', reading: 'かん', similars: ['親', '規', '覚'] },
    ],
    N2: [
        { correct: '壊', meaning: 'Destroy', reading: 'こわす', similars: ['懐', '壌', '塊'] },
        { correct: '懐', meaning: 'Nostalgia', reading: 'なつかしい', similars: ['壊', '壌', '塊'] },
        { correct: '繊', meaning: 'Slender', reading: 'せん', similars: ['織', '纏', '線'] },
        { correct: '織', meaning: 'Weave', reading: 'おる', similars: ['繊', '纏', '線'] },
        { correct: '微', meaning: 'Delicate', reading: 'び', similars: ['徴', '徹', '徳'] },
        { correct: '徴', meaning: 'Symptom/Sign', reading: 'ちょう', similars: ['微', '徹', '徳'] },
        { correct: '衝', meaning: 'Collision', reading: 'しょう', similars: ['衡', '街', '術'] },
        { correct: '衡', meaning: 'Balance', reading: 'こう', similars: ['衝', '街', '術'] },
        { correct: '漠', meaning: 'Vague', reading: 'ばく', similars: ['模', '膜', '幕'] },
        { correct: '模', meaning: 'Model', reading: 'も', similars: ['漠', '膜', '幕'] },
        { correct: '膜', meaning: 'Membrane', reading: 'まく', similars: ['漠', '模', '幕'] },
        { correct: '慌', meaning: 'Flustered', reading: 'あわてる', similars: ['荒', '慣', '惰'] },
        { correct: '荒', meaning: 'Rough/Wild', reading: 'あらい', similars: ['慌', '慣', '惰'] },
        { correct: '陰', meaning: 'Shadow', reading: 'かげ', similars: ['隠', '隣', '険'] },
        { correct: '隠', meaning: 'Hide', reading: 'かくす', similars: ['陰', '隣', '険'] },
        { correct: '賠', meaning: 'Compensate', reading: 'ばい', similars: ['培', '倍', '陪'] },
        { correct: '培', meaning: 'Cultivate', reading: 'ばい', similars: ['賠', '倍', '陪'] },
        { correct: '抑', meaning: 'Suppress', reading: 'おさえる', similars: ['仰', '迎', '柳'] },
        { correct: '仰', meaning: 'Look up', reading: 'あおぐ', similars: ['抑', '迎', '柳'] },
        { correct: '摘', meaning: 'Pick/Point out', reading: 'つむ', similars: ['適', '滴', '敵'] },
    ],
    N1: [
        { correct: '鬱', meaning: 'Depression', reading: 'うつ', similars: ['欝', '蔚', '鑿'] },
        { correct: '朦', meaning: 'Hazy', reading: 'もう', similars: ['朧', '矇', '蒙'] },
        { correct: '朧', meaning: 'Dim/Hazy', reading: 'おぼろ', similars: ['朦', '矇', '蒙'] },
        { correct: '鑑', meaning: 'Appraise', reading: 'かん', similars: ['鑒', '監', '艦'] },
        { correct: '監', meaning: 'Oversee', reading: 'かん', similars: ['鑑', '濫', '艦'] },
        { correct: '繕', meaning: 'Mend', reading: 'つくろう', similars: ['膳', '禅', '善'] },
        { correct: '膳', meaning: 'Meal tray', reading: 'ぜん', similars: ['繕', '禅', '善'] },
        { correct: '諮', meaning: 'Consult', reading: 'し', similars: ['諸', '誌', '諦'] },
        { correct: '諸', meaning: 'Various', reading: 'しょ', similars: ['諮', '誌', '諦'] },
        { correct: '遮', meaning: 'Intercept', reading: 'しゃ', similars: ['遭', '遡', '遜'] },
        { correct: '遭', meaning: 'Encounter', reading: 'そう', similars: ['遮', '遡', '遜'] },
        { correct: '嘱', meaning: 'Entrust', reading: 'しょく', similars: ['囑', '属', '燭'] },
        { correct: '属', meaning: 'Belong', reading: 'ぞく', similars: ['嘱', '囑', '燭'] },
        { correct: '戴', meaning: 'Receive humbly', reading: 'いただく', similars: ['載', '裁', '栽'] },
        { correct: '載', meaning: 'Load/Publish', reading: 'のせる', similars: ['戴', '裁', '栽'] },
        { correct: '裁', meaning: 'Judge/Cut', reading: 'さい', similars: ['戴', '載', '栽'] },
        { correct: '隷', meaning: 'Slave', reading: 'れい', similars: ['隸', '棣', '隶'] },
        { correct: '塡', meaning: 'Fill in', reading: 'てん', similars: ['填', '鎮', '慎'] },
        { correct: '彙', meaning: 'Collect/Category', reading: 'い', similars: ['彗', '彝', '彜'] },
        { correct: '頻', meaning: 'Frequent', reading: 'ひん', similars: ['瀕', '顰', '頒'] },
    ],
}

export const grammarByLevel = {
    N5: [
        { correct: ['私', 'は', '学生', 'です', '。'], english: 'I am a student.' },
        { correct: ['これ', 'は', '本', 'です', '。'], english: 'This is a book.' },
        { correct: ['毎日', '学校', 'に', '行きます', '。'], english: 'I go to school every day.' },
        { correct: ['水', 'を', '飲みます', '。'], english: 'I drink water.' },
        { correct: ['日本語', 'を', '勉強', 'します', '。'], english: 'I study Japanese.' },
        { correct: ['友達', 'と', '遊びます', '。'], english: 'I play with my friend.' },
        { correct: ['今日', 'は', '暑い', 'です', '。'], english: 'Today is hot.' },
        { correct: ['猫', 'が', '好き', 'です', '。'], english: 'I like cats.' },
        { correct: ['朝', 'ご飯', 'を', '食べます', '。'], english: 'I eat breakfast.' },
        { correct: ['あの', '人', 'は', '先生', 'です', '。'], english: 'That person is a teacher.' },
        { correct: ['駅', 'は', 'どこ', 'ですか', '？'], english: 'Where is the station?' },
        { correct: ['テレビ', 'を', '見ます', '。'], english: 'I watch television.' },
        { correct: ['明日', '来ます', '。'], english: 'I will come tomorrow.' },
        { correct: ['この', 'りんご', 'は', '赤い', 'です', '。'], english: 'This apple is red.' },
        { correct: ['部屋', 'に', '入ります', '。'], english: 'I enter the room.' },
    ],
    N4: [
        { correct: ['毎日', '日本語', 'を', '勉強', 'して', 'います', '。'], english: 'I study Japanese every day.' },
        { correct: ['東京', 'に', '行き', 'たい', 'です', '。'], english: 'I want to go to Tokyo.' },
        { correct: ['この', '本', 'は', 'とても', '面白い', 'です', '。'], english: 'This book is very interesting.' },
        { correct: ['昨日', '友達', 'と', '映画', 'を', '見ました', '。'], english: 'I watched a movie with a friend yesterday.' },
        { correct: ['日本', 'の', '食べ物', 'が', '好き', 'です', '。'], english: 'I like Japanese food.' },
        { correct: ['駅', 'まで', '歩いて', '10分', 'かかります', '。'], english: 'It takes 10 minutes to walk to the station.' },
        { correct: ['先生', 'に', '質問', 'を', 'しました', '。'], english: 'I asked the teacher a question.' },
        { correct: ['電車', 'の', '中', 'で', '本', 'を', '読みます', '。'], english: 'I read books on the train.' },
        { correct: ['母', 'が', '作った', '料理', 'は', 'おいしい', 'です', '。'], english: 'The food my mother made is delicious.' },
        { correct: ['彼', 'は', '英語', 'が', '上手', 'です', '。'], english: 'He is good at English.' },
        { correct: ['すみません', '、', 'トイレ', 'は', 'どこ', 'ですか', '？'], english: 'Excuse me, where is the toilet?' },
        { correct: ['寝る', '前', 'に', '歯', 'を', '磨きます', '。'], english: 'I brush my teeth before going to bed.' },
        { correct: ['来週', 'の', '月曜日', 'に', '会議', 'が', 'あります', '。'], english: 'There is a meeting next Monday.' },
        { correct: ['もし', '時間', 'が', 'あれば', '手伝って', 'ください', '。'], english: 'If you have time, please help.' },
        { correct: ['このレストラン', 'は', '予約', 'が', '必要', 'です', '。'], english: 'This restaurant requires a reservation.' },
    ],
    N3: [
        { correct: ['明日', '天気', 'が', 'よければ', '公園', 'に', '行きます', '。'], english: 'If the weather is good tomorrow, I will go to the park.' },
        { correct: ['雨', 'が', '降って', 'いる', 'から', '傘', 'を', '持って', 'いきましょう', '。'], english: "It's raining, so let's take an umbrella." },
        { correct: ['日本', 'に', '来て', 'から', '3年', 'に', 'なります', '。'], english: 'It has been 3 years since I came to Japan.' },
        { correct: ['彼女', 'は', 'ピアノ', 'を', '弾く', 'こと', 'が', 'できます', '。'], english: 'She can play the piano.' },
        { correct: ['この', '問題', 'は', '難しすぎて', '解けません', '。'], english: 'This problem is too difficult to solve.' },
        { correct: ['彼', 'が', '来る', 'かどうか', 'わかりません', '。'], english: "I don't know whether he will come." },
        { correct: ['毎朝', 'ジョギング', 'する', 'ように', 'して', 'います', '。'], english: 'I try to jog every morning.' },
        { correct: ['先生', 'に', '褒められて', 'うれしかった', 'です', '。'], english: 'I was happy to be praised by the teacher.' },
        { correct: ['この', '映画', 'は', '見る', '価値', 'が', 'あります', '。'], english: 'This movie is worth watching.' },
        { correct: ['忙しい', 'にもかかわらず', '手伝って', 'くれました', '。'], english: 'Despite being busy, they helped me.' },
        { correct: ['会議', 'の', '結果', 'について', '報告', 'します', '。'], english: 'I will report on the results of the meeting.' },
        { correct: ['経験', 'が', 'ない', 'わけでは', 'ありません', '。'], english: "It's not that I have no experience." },
        { correct: ['遅刻', 'しない', 'ように', '早く', '出ました', '。'], english: 'I left early so as not to be late.' },
        { correct: ['日本語', 'が', '上手', 'に', 'なる', 'ために', '毎日', '練習', 'します', '。'], english: 'I practice every day to become good at Japanese.' },
        { correct: ['田中さん', 'に', 'よると', '会議', 'は', '中止', 'だ', 'そうです', '。'], english: 'According to Mr. Tanaka, the meeting is cancelled.' },
    ],
    N2: [
        { correct: ['彼', 'は', '努力', 'した', 'にもかかわらず', '試験', 'に', '落ちて', 'しまった', '。'], english: 'Despite his efforts, he failed the exam.' },
        { correct: ['この', '計画', 'を', '実行', 'する', 'にあたって', '十分な', '準備', 'が', '必要', 'です', '。'], english: 'Sufficient preparation is necessary when carrying out this plan.' },
        { correct: ['彼女', 'の', '話', 'を', '聞く', 'につれて', '事情', 'が', 'わかって', 'きた', '。'], english: 'As I listened to her story, I came to understand the situation.' },
        { correct: ['環境', '問題', 'は', '深刻化', 'する', '一方', 'です', '。'], english: 'Environmental problems are only getting worse.' },
        { correct: ['経済', 'が', '悪化', 'した', '結果', '失業率', 'が', '上がった', '。'], english: 'As a result of the economic decline, the unemployment rate rose.' },
        { correct: ['あの', '映画', 'は', '見れば', '見る', 'ほど', '面白い', '。'], english: 'The more you watch that movie, the more interesting it is.' },
        { correct: ['この', '問題', 'に', '関して', 'は', '私', 'に', '任せて', 'ください', '。'], english: 'Please leave this problem to me.' },
        { correct: ['社長', 'として', 'の', '責任', 'を', '果たさ', 'なければ', 'なりません', '。'], english: 'I must fulfill my responsibilities as president.' },
        { correct: ['技術', 'の', '進歩', 'に', '伴い', '生活', 'が', '便利', 'に', 'なった', '。'], english: 'Life has become more convenient with advances in technology.' },
        { correct: ['結論', 'から', '言えば', 'この', '計画', 'は', '無理', 'です', '。'], english: 'In conclusion, this plan is impossible.' },
        { correct: ['予算', 'の', '関係', '上', '計画', 'を', '変更', 'せざるを得ない', '。'], english: 'Due to budget constraints, we have no choice but to change the plan.' },
        { correct: ['彼', 'は', '医者', 'で', 'ある', 'と同時に', '作家', 'でもある', '。'], english: 'He is a doctor and at the same time a writer.' },
        { correct: ['新しい', '法律', 'が', '施行', 'された', 'のを', 'きっかけに', '社会', 'が', '変わった', '。'], english: 'Society changed triggered by the new law.' },
        { correct: ['いくら', '説明', 'しても', '彼', 'は', '理解', 'しようと', 'しない', '。'], english: 'No matter how much I explain, he refuses to understand.' },
        { correct: ['この', '地域', 'は', '自然', 'が', '豊か', 'な', '反面', '交通', 'が', '不便', 'です', '。'], english: 'This area is rich in nature, but on the other hand transportation is inconvenient.' },
    ],
    N1: [
        { correct: ['彼', 'は', '天才', 'と', '言われる', 'だけ', 'あって', '発想', 'が', '独創的', 'だ', '。'], english: 'He is said to be a genius, and indeed his ideas are original.' },
        { correct: ['今更', '後悔', 'した', 'ところで', '取り返し', 'が', 'つかない', '。'], english: "Even if you regret it now, it's too late to fix." },
        { correct: ['国民', 'の', '安全', 'を', '確保', 'する', 'べく', '政府', 'は', '対策', 'を', '講じた', '。'], english: 'The government took measures to ensure the safety of citizens.' },
        { correct: ['彼女', 'は', '若い', 'ながら', 'も', '経営者', 'として', '手腕', 'を', '発揮', 'して', 'いる', '。'], english: 'Despite being young, she demonstrates her ability as a manager.' },
        { correct: ['この', '法案', 'が', '可決', 'された', '暁', 'には', '社会', 'が', '大きく', '変わる', 'だろう', '。'], english: 'When this bill is passed, society will change greatly.' },
        { correct: ['経済', '危機', 'を', '乗り越える', 'には', '官民', '一体', 'と', 'なって', '取り組む', '必要', 'が', 'ある', '。'], english: 'To overcome the economic crisis, public and private sectors must work together.' },
        { correct: ['先人', 'たち', 'の', '知恵', 'なくして', 'は', '今日', 'の', '繁栄', 'は', 'なかった', 'であろう', '。'], english: "Without the wisdom of our predecessors, today's prosperity would not have existed." },
        { correct: ['彼', 'の', '態度', 'たるや', '目', 'に', '余る', 'ものが', 'ある', '。'], english: 'His attitude is truly beyond tolerance.' },
        { correct: ['この', '作品', 'は', '芸術性', 'もさることながら', '社会的', 'メッセージ', 'が', '強い', '。'], english: "This work has a strong social message, not to mention its artistic value." },
        { correct: ['災害', 'に', '備え', 'て', 'おく', 'に', '越した', 'こと', 'は', 'ない', '。'], english: "It's best to prepare for disasters." },
        { correct: ['彼', 'は', '証拠', 'を', '突きつけ', 'られる', 'や', 'いなや', '自白', 'した', '。'], english: 'The moment the evidence was presented, he confessed.' },
        { correct: ['人口', '減少', '問題', 'は', '対岸', 'の', '火事', 'では', '済まされない', '。'], english: 'The population decline issue cannot be treated as someone else\'s problem.' },
        { correct: ['この', '小説', 'は', '読めば', '読む', 'ほど', '考えさせ', 'られる', '。'], english: 'The more you read this novel, the more it makes you think.' },
        { correct: ['政府', 'の', '方針', 'いかん', 'に', 'よっては', '今後', '大きな', '影響', 'が', '出る', '。'], english: "Depending on the government's policy, there may be significant impact." },
        { correct: ['彼', 'の', '功績', 'は', '称賛', 'に', '値する', '。'], english: 'His achievements deserve praise.' },
    ],
}
